CREATE database ORDER_PROCESSING
USE ORDER_PROCESSING
CREATE TABLE `order_processing`.`company` (
  `COMPANY_ID` VARCHAR(10) NOT NULL,
  `COMPANY_NAME` VARCHAR(50) NOT NULL,
  `COMPANY_ADDRESS_LINE1` VARCHAR(40) NOT NULL,
  `COMPANY_ADDRESS_CITY` VARCHAR(45) NOT NULL,
  `COMPANY_ADDRESS_STATE` VARCHAR(45) NOT NULL,
  `COMPANY_GST_NUMBER` VARCHAR(15) NOT NULL,
   `COMPANY_PINCODE` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`COMPANY_ID`)
  );

CREATE TABLE `order_processing`.`customer` (
  `CUSTOMER_ID` VARCHAR(10) NOT NULL,
  `CUSTOMER_NAME` VARCHAR(30) NOT NULL,
  `CUSTOMER_GST` VARCHAR(15) NOT NULL,
  `CUSTOMER_ADDRESS_LINE1` VARCHAR(40) NOT NULL,
  `CUSTOMER_ADDRESS_CITY` VARCHAR(45) NOT NULL,
  `CUSTOMER_ADDRESS_STATE` VARCHAR(45) NOT NULL,
  `CUSTOMER_EMAIL` VARCHAR(30) NOT NULL,
  `CUSTOMER_CONTACT` LONGTEXT NOT NULL,
  `CUSTOMER_PINCODE` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
);

CREATE TABLE `order_processing`.`product` (
  `PRODUCT_ID` INT NOT NULL,
  `PRODUCT_NAME` VARCHAR(20) NOT NULL,
  `PRODUCT_PRICE` INT NOT NULL,
  `PRODUCT_CATEGORY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
);

CREATE TABLE `order_processing`.`order` (
  `ORDER_ID` VARCHAR(10) NOT NULL,
  `ORDER_DATE` DATE NOT NULL,
  PRIMARY KEY (`ORDER_ID`));

ALTER TABLE `order_processing`.`company` 
ADD COLUMN `COMPANY_PINCODE` VARCHAR(45) NULL AFTER `COMPANY_GST_NUMBER`;

CREATE TABLE `order_processing`.`order_line` (
  `ORDER_ID` VARCHAR(10) NOT NULL,
  `CUSTOMER_SHIPPING_ADDRESS_LINE1` VARCHAR(40) NOT NULL,
  `CUSTOMER_SHIPPING_ADDRESS_CITY` VARCHAR(45) NULL,
  `CUSTOMER_SHIPPING_ADDRESS_STATE` VARCHAR(45) NULL,
  PRIMARY KEY (`ORDER_ID`),
  CONSTRAINT `CUSTOMER_ID`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `order_processing`.`customer` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE `order_processing`.`invoice` (
  `INVOICE_ID` VARCHAR(10) NOT NULL,
  `INVOICE_DATE` DATE NOT NULL,
  `TOTAL_GST_VALUE` INT NOT NULL,
  `TOATL_INVOICE_VALUE` INT NOT NULL,
  `INVOICE_STATUS` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`INVOICE_ID`)
  );
  
CREATE TABLE `order_processing`.`product_line` (
  `PRODUCT_ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  CONSTRAINT `INVOICE_ID`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `order_processing`.`invoice` (`INVOICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
